name: Test

on:
    push:
        tags: ["*"]
    pull_request:
    workflow_dispatch:

jobs:
    check-version:
        name: python
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Install the project
              run: uv sync --locked --all-extras --dev

            - name: Run tests
              run: uv run utils/check_version_sync.py && uv run utils/check_version_newer.py

    test:
        name: test
        runs-on: ubuntu-latest
        needs: check-version
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy, rustfmt
            - name: Cache Cargo
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-

            - name: Format check
              run: cargo fmt --all -- --check

            - name: Clippy
              run: cargo clippy --workspace --all-targets -- -D warnings

            - name: Rust tests
              run: cargo test --workspace

            - name: Install uv
              run: curl -LsSf https://astral.sh/uv/install.sh | sh

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Build and install package
              working-directory: kiru-py
              run: |
                  uv venv
                  source .venv/bin/activate
                  maturin develop --release

            - name: Run Python tests
              working-directory: kiru-py
              run: |
                  source .venv/bin/activate
                  uv sync --dev
                  uv pytest python/test.py
